/*
 * RosBE Options Dialog (options.c)
 *
 * Copyright 2007 by Maarten Bosma
 *                   Pierre Schweitzer
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program ; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#include <windows.h>
#include <stdio.h>
#include <shlobj.h>
#include <wchar.h>
#include "resources.h"

#define MINGWVERSION L"\\4.1.3"

typedef LPITEMIDLIST (CALLBACK* ILCREATEFROMPATHW)(LPCWSTR path);

// note: do not change the order - theses are the color under winxp they might differ in another OSes
WCHAR *Colors[] = { L"black", L"dark blue", L"dark green", L"turquoise", L"dark red", L"purple",
    L"ochar", L"light grey", L"dark grey", L"light blue", L"light green",
    L"cyan", L"light red", L"magenta", L"yellow", L"white"
};

// note: do not change the order - it matches to previous order
COLORREF ColorsRGB[] = { 0x00000000, 0x00800000, 0x00008000, 0x00808000, 0x00000080, 0x00800080,
    0x00008080, 0x00c0c0c0, 0x00808080, 0x00ff0000, 0x0000ff00,
    0x00ffff00, 0x000000ff, 0x00ff00ff, 0x0000ffff, 0x00ffffff
};

HINSTANCE hInstance;

INT
WriteSettings(HWND hwnd)
{
    int foreground, background;
    BOOL showtime, writelog, useccache, strip, otherobj, otherout;
    WCHAR logdir[MAX_PATH], objdir[MAX_PATH], outdir[MAX_PATH], mingwpath[MAX_PATH], checkmgw[MAX_PATH], checklog[MAX_PATH];
    WCHAR msgerror[256];
    HANDLE hFile;
    FILE *pFile;

    showtime = (SendDlgItemMessage(hwnd, ID_SHOWBUILDTIME, BM_GETCHECK, 0, 0) == BST_CHECKED);
    writelog = (SendDlgItemMessage(hwnd, ID_SAVELOGS, BM_GETCHECK, 0, 0) == BST_CHECKED);
    useccache = (SendDlgItemMessage(hwnd, ID_USECCACHE, BM_GETCHECK, 0, 0) == BST_CHECKED);
    strip = (SendDlgItemMessage(hwnd, ID_STRIP, BM_GETCHECK, 0, 0) == BST_CHECKED);
    otherobj = (SendDlgItemMessage(hwnd, ID_OTHEROBJ, BM_GETCHECK, 0, 0) == BST_CHECKED);
    otherout = (SendDlgItemMessage(hwnd, ID_OTHEROUT, BM_GETCHECK, 0, 0) == BST_CHECKED);
    foreground = (UINT)SendDlgItemMessage(hwnd, IDC_FONT, CB_GETCURSEL, 0, 0);
    background = (UINT)SendDlgItemMessage(hwnd, IDC_BACK, CB_GETCURSEL, 0, 0);
    GetDlgItemText(hwnd, ID_LOGDIR, logdir, MAX_PATH);
    GetDlgItemText(hwnd, ID_MGWDIR, mingwpath, MAX_PATH);
    GetDlgItemText(hwnd, ID_OBJDIR, objdir, MAX_PATH);
    GetDlgItemText(hwnd, ID_OUTDIR, outdir, MAX_PATH);

    if (writelog)
    {
        GetCurrentDirectory(MAX_PATH, checklog);
        if (SetCurrentDirectory(logdir))
        {
            SetCurrentDirectory(checklog);
        }
        else
        {
            if (!CreateDirectory(logdir, NULL))
            {
                LoadString(hInstance, MSG_DIREFAILED, msgerror, 256);
                MessageBox(NULL, msgerror, NULL, MB_ICONERROR);
                return FALSE;
            }
        }
    }

    wcscpy(checkmgw, mingwpath);
    if ((wcslen(checkmgw) + wcslen(L"\\bin\\gcc.exe")) < MAX_PATH)
        wcscat(checkmgw, L"\\bin\\gcc.exe");
    hFile = CreateFile(checkmgw, 0, 0, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
    if (hFile == INVALID_HANDLE_VALUE)
    {
        LoadString(hInstance, MSG_NOGCCFOUND, msgerror, 256);
        MessageBox(NULL, msgerror, NULL, MB_ICONERROR);
        return FALSE;
    }
    CloseHandle(hFile);

    pFile = fopen("rosbe-options.cmd", "w");
    if (pFile)
    {
        fprintf(pFile, "::\n");
        fprintf(pFile, ":: This file has been automatically generated by the ReactOS\n");
        fprintf(pFile, ":: Build Environment options utility.\n");
        fprintf(pFile, "::\n\n");
        fprintf(pFile, "color %X%X\n", background, foreground);
        fprintf(pFile, "set _ROSBE_SHOWTIME=%d\n", showtime);
        fprintf(pFile, "set _ROSBE_USECCACHE=%d\n", useccache);
        fprintf(pFile, "set _ROSBE_STRIP=%d\n", strip);
        fprintf(pFile, "set _ROSBE_WRITELOG=%d\n", writelog);
        fprintf(pFile, "set _ROSBE_LOGDIR=%S\n", logdir);
        fprintf(pFile, "set _ROSBE_MINGWPATH=%S\n", mingwpath);
        fprintf(pFile, "set _ROSBE_OBJPATH=%S\n", objdir);
        fprintf(pFile, "set _ROSBE_OUTPATH=%S\n", outdir);
        fclose(pFile);
        return TRUE;
    }
    LoadString(hInstance, MSG_FILEFAILED, msgerror, 256);
    MessageBox(NULL, msgerror, NULL, MB_ICONERROR);
    return FALSE;
}

INT_PTR CALLBACK
DlgProc(HWND Dlg, UINT Msg, WPARAM wParam, LPARAM lParam)
{
    static HICON hIcon;

    switch (Msg)
    {
        case WM_INITDIALOG:
        {
            WCHAR Path[MAX_PATH];
            UINT i;

            hIcon = LoadImage( hInstance,
                               MAKEINTRESOURCE(ID_OPTICON),
                               IMAGE_ICON,
                               GetSystemMetrics(SM_CXSMICON),
                               GetSystemMetrics(SM_CYSMICON),
                               0);
            if(hIcon)
                SendMessage(Dlg, WM_SETICON, ICON_SMALL, (LPARAM)hIcon);

            for(i = 0; i < sizeof(Colors) / sizeof(char *); i++)
            {
                SendDlgItemMessage(Dlg, IDC_BACK, CB_ADDSTRING, 0, (LPARAM) (Colors[i]));
                SendDlgItemMessage(Dlg, IDC_FONT, CB_ADDSTRING, 0, (LPARAM) (Colors[i]));
            }
            SendDlgItemMessage(Dlg, IDC_FONT, CB_SETCURSEL, 0xa, 0);
            SendDlgItemMessage(Dlg, IDC_BACK, CB_SETCURSEL, 0, 0);
            GetCurrentDirectory(MAX_PATH, Path);
            if ((wcslen(Path) + wcslen(MINGWVERSION)) < MAX_PATH)
                wcscat(Path, MINGWVERSION);
            SetDlgItemText(Dlg, ID_MGWDIR, Path);

            return TRUE;
        }

        case WM_COMMAND:
        {
            if ((HIWORD(wParam) == CBN_SELCHANGE) && ((LOWORD(wParam) == IDC_FONT) || (LOWORD(wParam) == IDC_BACK)))
            {
                RECT rcWnd;
                GetClientRect(GetDlgItem(Dlg, ID_EXAMPLE), &rcWnd);
                InvalidateRect(GetDlgItem(Dlg, ID_EXAMPLE), &rcWnd, FALSE);
                EnableWindow(GetDlgItem(Dlg, ID_OK), TRUE);
            }
            else
            {
                switch (wParam)
                {
                    case ID_OK:
                    {
                       if (!WriteSettings(Dlg))
                       break;
                    }
                    case ID_CANCEL:
                    {
                        PostMessage(Dlg, WM_CLOSE, 0, 0);
                        break;
                    }
                    case ID_BROWSE:
                    case ID_BROWSEMGW:
                    case ID_BROWSEOBJ:
                    case ID_BROWSEOUT:
                    {
                        BROWSEINFO PathInfo;
                        LPITEMIDLIST pidl;
                        INT Control = ID_LOGDIR;
                        WCHAR path[MAX_PATH];

                        ZeroMemory(&PathInfo, sizeof(BROWSEINFO));
                        PathInfo.hwndOwner = Dlg;
                        PathInfo.lpszTitle = L"Please choose a directory where the the logs should be stored:";

                        if (wParam == ID_BROWSEMGW)
                        {
                            HINSTANCE hDLL;
                            ILCREATEFROMPATHW ILCreateFromPathW;
                            Control = ID_MGWDIR;
                            PathInfo.lpszTitle = L"Please choose the directory where MingW is located:";
                            hDLL = LoadLibrary(L"shell32.dll");
                            if (hDLL)
                            {
                                ILCreateFromPathW = (ILCREATEFROMPATHW)GetProcAddress(hDLL, "ILCreateFromPathW");
                                if (ILCreateFromPathW)
                                {
                                    GetDlgItemText(Dlg, ID_MGWDIR, path, MAX_PATH);
                                    PathInfo.pidlRoot = ILCreateFromPathW(path);
                                }
                                FreeLibrary(hDLL);
                            }
                        }
                        if (wParam == ID_BROWSEOBJ)
                        {
                            HINSTANCE hDLL;
                            ILCREATEFROMPATHW ILCreateFromPathW;
                            Control = ID_OBJDIR;
                            PathInfo.lpszTitle = L"Please choose the directory where you want to save OBJ Files to:";
                            hDLL = LoadLibrary(L"shell32.dll");
                            if (hDLL)
                            {
                                ILCreateFromPathW = (ILCREATEFROMPATHW)GetProcAddress(hDLL, "ILCreateFromPathW");
                                if (ILCreateFromPathW)
                                {
                                    GetDlgItemText(Dlg, ID_OBJDIR, path, MAX_PATH);
                                    PathInfo.pidlRoot = ILCreateFromPathW(path);
                                }
                                FreeLibrary(hDLL);
                            }
                        }
                        if (wParam == ID_BROWSEOUT)
                        {
                            HINSTANCE hDLL;
                            ILCREATEFROMPATHW ILCreateFromPathW;
                            Control = ID_OUTDIR;
                            PathInfo.lpszTitle = L"Please choose the directory where you want to save OBJ Files to:";
                            hDLL = LoadLibrary(L"shell32.dll");
                            if (hDLL)
                            {
                                ILCreateFromPathW = (ILCREATEFROMPATHW)GetProcAddress(hDLL, "ILCreateFromPathW");
                                if (ILCreateFromPathW)
                                {
                                    GetDlgItemText(Dlg, ID_OUTDIR, path, MAX_PATH);
                                    PathInfo.pidlRoot = ILCreateFromPathW(path);
                                }
                                FreeLibrary(hDLL);
                            }
                        }
                        pidl = SHBrowseForFolder(&PathInfo);
                        if (pidl)
                        {
                            if (SHGetPathFromIDList(pidl, path))
                            {
                                SetDlgItemText(Dlg, Control, path);
                            }
                        }
                    }
                    case ID_STRIP:
                    case ID_USECCACHE:
                    case ID_SHOWBUILDTIME:
                    {
                        EnableWindow(GetDlgItem(Dlg, ID_OK), TRUE);
                        break;
                    }
                    case ID_SAVELOGS:
                    {
                        BOOL WriteLogSet;
                        WriteLogSet = SendDlgItemMessage(Dlg, ID_SAVELOGS, BM_GETCHECK, 0, 0) == BST_CHECKED;
                        EnableWindow(GetDlgItem(Dlg, ID_BROWSE), WriteLogSet);
                        EnableWindow(GetDlgItem(Dlg, ID_LOGDIR), WriteLogSet);
                        break;
                    }
                    case ID_OTHEROBJ:
                    {
                        BOOL WriteLogSet;
                        WriteLogSet = SendDlgItemMessage(Dlg, ID_OTHEROBJ, BM_GETCHECK, 0, 0) == BST_CHECKED;
                        EnableWindow(GetDlgItem(Dlg, ID_BROWSEOBJ), WriteLogSet);
                        EnableWindow(GetDlgItem(Dlg, ID_OBJDIR), WriteLogSet);
                        EnableWindow(GetDlgItem(Dlg, ID_OK), TRUE);
                        break;
                    }
                    case ID_OTHEROUT:
                    {
                        BOOL WriteLogSet;
                        WriteLogSet = SendDlgItemMessage(Dlg, ID_OTHEROUT, BM_GETCHECK, 0, 0) == BST_CHECKED;
                        EnableWindow(GetDlgItem(Dlg, ID_BROWSEOUT), WriteLogSet);
                        EnableWindow(GetDlgItem(Dlg, ID_OUTDIR), WriteLogSet);
                        EnableWindow(GetDlgItem(Dlg, ID_OK), TRUE);
                        break;
                    }
                }

            }
            return FALSE;
        }

        case WM_CTLCOLORSTATIC:
        {
            if((HWND)lParam == GetDlgItem(Dlg, ID_EXAMPLE))
            {
                SetTextColor((HDC)wParam, ColorsRGB[SendDlgItemMessage(Dlg, IDC_FONT, CB_GETCURSEL, 0, 0)]);
                SetBkColor((HDC)wParam, ColorsRGB[SendDlgItemMessage(Dlg, IDC_BACK, CB_GETCURSEL, 0, 0)]);
                return (LONG)CreateSolidBrush(ColorsRGB[SendDlgItemMessage(Dlg, IDC_BACK, CB_GETCURSEL, 0, 0)]);
            }
            break;
        }

        case WM_DESTROY:
        {
            if (hIcon)
                DestroyIcon(hIcon);
        }

        case WM_CLOSE:
        {
            EndDialog(Dlg, 0);
            return TRUE;
        }
    }
    return FALSE;
}

int WINAPI
WinMain(HINSTANCE hInst, HINSTANCE hPrevInst, LPSTR cmdline, int cmdshow)
{
    hInstance = hInst;

    DialogBox(hInst, MAKEINTRESOURCE(ID_DIALOG), 0, DlgProc);
    return 0;
}
