; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	f:\reactos\trunk\documentation\audit\switch_default\switch_default.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	??_C@_04DFOOMHBJ@Bar?6?$AA@			; `string'
PUBLIC	??_C@_04DEEPCGMJ@Foo?6?$AA@			; `string'
PUBLIC	_wmain
EXTRN	__imp__printf:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT ??_C@_04DFOOMHBJ@Bar?6?$AA@
; File f:\reactos\trunk\documentation\audit\switch_default\switch_default.cpp
CONST	SEGMENT
??_C@_04DFOOMHBJ@Bar?6?$AA@ DB 'Bar', 0aH, 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_04DEEPCGMJ@Foo?6?$AA@
CONST	SEGMENT
??_C@_04DEEPCGMJ@Foo?6?$AA@ DB 'Foo', 0aH, 00H		; `string'
CONST	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _wmain
_TEXT	SEGMENT
tv64 = -208						; size = 4
_a$ = -8						; size = 4
_argc$ = 8						; size = 4
_argv$ = 12						; size = 4
_wmain	PROC						; COMDAT

; 8    : {

	push	ebp
	mov	ebp, esp
	sub	esp, 208				; 000000d0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-208]
	mov	ecx, 52					; 00000034H
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 9    : 	int a = 1;

	mov	DWORD PTR _a$[ebp], 1

; 10   : 
; 11   : 	switch(a) {

	mov	eax, DWORD PTR _a$[ebp]
	mov	DWORD PTR tv64[ebp], eax

; 12   : 	default:
; 13   : 		printf("Foo\n");

	mov	esi, esp
	push	OFFSET ??_C@_04DEEPCGMJ@Foo?6?$AA@
	call	DWORD PTR __imp__printf
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp

; 14   : 		break;
; 15   : 	}
; 16   : 
; 17   : 	printf("Bar\n");

	mov	esi, esp
	push	OFFSET ??_C@_04DFOOMHBJ@Bar?6?$AA@
	call	DWORD PTR __imp__printf
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp

; 18   : 
; 19   : 	return 0;

	xor	eax, eax

; 20   : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 208				; 000000d0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_wmain	ENDP
_TEXT	ENDS
END
