//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsgTrans.Library.Tests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\GUI\\Resources\\ntstatus.xml")]
        public string NtStatusXml {
            get {
                return ((string)(this["NtStatusXml"]));
            }
            set {
                this["NtStatusXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\GUI\\Resources\\winerror.xml")]
        public string WinerrorXml {
            get {
                return ((string)(this["WinerrorXml"]));
            }
            set {
                this["WinerrorXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\GUI\\Resources\\hresult.xml")]
        public string HresultXml {
            get {
                return ((string)(this["HresultXml"]));
            }
            set {
                this["HresultXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\GUI\\Resources\\bugcheck.xml")]
        public string BugcheckXml {
            get {
                return ((string)(this["BugcheckXml"]));
            }
            set {
                this["BugcheckXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\GUI\\Resources\\wm.xml")]
        public string WmXml {
            get {
                return ((string)(this["WmXml"]));
            }
            set {
                this["WmXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.reactos.org/bugzilla/show_bug.cgi?id={0}")]
        public string BugUrl {
            get {
                return ((string)(this["BugUrl"]));
            }
            set {
                this["BugUrl"] = value;
            }
        }
    }
}
