#!/bin/bash

TIME="$(dirname $0)/time"

OBJ=${ROS_INTERMEDIATE:=obj-i386}
OUTPUT=${ROS_OUTPUT:=output-i386}

$TIME bash -c "( 
    echo -e '\n* Getting revision number...'
    export REV=$(svnversion .)
    echo -e "* Revision $REV.\n"
    
    source "checkrev"
    
    echo -e '\n* Cleaning...'

    if [ -f makefile.auto ]; then
        echo '  * makefile.auto'
        rm makefile.auto
    fi

    echo '  * obj-i386'
    rm -rf $OBJ
    echo '  * output-i386'
    rm -rf $OUTPUT
    echo '  * reactos'
    rm -rf "reactos."
    echo '  * CD images'
    rm -f *.iso
    
    if [ $# -eq 1 ]; then
        if [ "${1}" = "rel" ]; then
            echo -e '\n* Recreating config.rbuild...'
            cat config.template.rbuild | sed 's/\"DBG\" value=\"1\"/\"DBG\" value=\"0\"/' > config.rbuild
        fi
    fi

    exit 0
)"
