#!/bin/bash

TIME="$(dirname $0)/time"

OBJ=${ROS_INTERMEDIATE:=obj-i386}
OUTPUT=${ROS_OUTPUT:=output-i386}

$TIME bash -c "( 
    echo -e '\n* Cleaning...'

    if [ -f makefile.auto ]; then
        echo '  * makefile.auto'
        rm makefile.auto
    fi

    echo '  * obj-i386'
    rm -rf $OBJ
    echo '  * output-i386'
    rm -rf $OUTPUT
    echo '  * CD images'
    rm -f *.iso

    echo -e '\n* Deleting unversioned files from the source...'
    ../../svn-clean --exclude '^.buildbot-sourcedata'

    if [ $# -eq 1 ]; then
        echo -e '\n* Recreating config.rbuild...'
        if [ "${1}" = "rel" ]; then
            cat config.template.rbuild | sed 's/"DBG" value="1"/"DBG" value="0"/' > config.rbuild
        fi
    fi

    echo -e '\n* Compiling tools...'
    ../../build clean
    echo -e '* Done compiling tools.'

    exit 0
)"
