#!/bin/sh

HERE="$(pwd $(dirname $0))"
TIME=$HERE/time

SILENCE=$HERE/silence
BUILDLOG=$HERE/simulate.log

cd fullrel/build
export BUILDLOG

echo "*** STEP 1: svn update"|tee -a $BUILDLOG
$TIME $SILENCE svn update --revision HEAD --non-interactive
echo

echo "*** STEP 2: makeclean"|tee -a $BUILDLOG
$TIME $SILENCE ../../makeclean
echo

echo "*** STEP 3: build all"|tee -a $BUILDLOG
$TIME $SILENCE ../../build
echo

echo "*** STEP 4: build bootcd"|tee -a $BUILDLOG
$TIME $SILENCE ../../build bootcd
echo

echo "*** STEP 5: build livecd"|tee -a $BUILDLOG
$TIME $SILENCE ../../build livecd
echo

echo "*** STEP 6: uploadiso dbg"|tee -a $BUILDLOG
#$TIME $SILENCE ../../uploadiso dbg
echo
