#!/bin/sh

export PATH=tools/ppc.lost+found:$PATH

if [ ! -d tmp-ppc ] ; then
	mkdir tmp-ppc || echo "Could not make temp dir"
fi

$OLDMAKE \
	ARCH=powerpc \
	HOST=mingw32-linux \
	PREFIX=powerpc-unknown-elf \
	ROS_TEMPORARY=tmp-ppc \
	ROS_INTERMEDIATE=obj-ppc \
	ROS_OUTPUT=output-ppc \
	ROS_PREFIX=powerpc-unknown-elf \
	ROS_INSTALL=rosppc \
	ROS_AUTOMAKE=makefile.ppc \
	ROS_RBUILDFLAGS=-rReactOS-ppc.rbuild \
	$*
